// <auto-generated />
using Assignment1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment1.Migrations.Technician
{
    [DbContext(typeof(TechnicianContext))]
    partial class TechnicianContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment1.Models.Technician", b =>
                {
                    b.Property<int>("techId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("techEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("techName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("techPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("techId");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            techId = 1,
                            techEmail = "mike@gmail.com",
                            techName = "Mike",
                            techPhone = "555-777-5533"
                        },
                        new
                        {
                            techId = 2,
                            techEmail = "mike@gmail.com",
                            techName = "Mike2",
                            techPhone = "555-777-5533"
                        },
                        new
                        {
                            techId = 3,
                            techEmail = "mike@gmail.com",
                            techName = "Mike3",
                            techPhone = "555-777-5533"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
